[chore] buildコマンドを修正

diff --git a/.github/workflows/build-working.yml b/.github/workflows/build-working.yml
--- a/.github/workflows/build-working.yml
+++ b/.github/workflows/build-working.yml
@@ -38,6 +38,5 @@ jobs:
           platform: 'macOS'
         run: |
           if [ $scheme = default ]; then scheme=$(cat default); fi
-          if [ "`ls -A | grep -i \\.xcworkspace\$`" ]; then filetype_parameter="workspace" && file_to_build="`ls -A | grep -i \\.xcworkspace\$`"; else filetype_parameter="project" && file_to_build="`ls -A | grep -i \\.xcodeproj\$`"; fi
-          file_to_build=`echo $file_to_build | awk '{$1=$1;print}'`
-          xcodebuild build-for-testing -scheme "$scheme" -"$filetype_parameter" "$file_to_build" -destination "platform=$platform"
+          if [ -d "$PWD/$scheme.xcodeproj" ]; then filetype_parameter="project" && file_to_build="$scheme.xcodeproj"; elif [ -d "$PWD/$scheme.xcworkspace" ]; then filetype_parameter="workspace" && file_to_build="$scheme.xcworkspace"; else echo "ERROR: Xcode project or workspace not found."; exit 1; fi
+          xcodebuild build -scheme "$scheme" -"$filetype_parameter" "$file_to_build" -configuration Release
